#include "arduino_secrets.h"
// Servo - Version: Latest 
#include <Servo.h>

/* 
  Sketch generated by the Arduino IoT Cloud Thing "Robot"
  https://create.arduino.cc/cloud/things/579ba83f-258d-4ece-bc12-4459e6456c5a 

  Arduino IoT Cloud Properties description

  The following variables are automatically generated and updated when changes are made to the Thing properties

  int servoLeft;
  int servoRight;

  Properties which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

Servo left;
Servo right;

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
  
  left.attach(2);
  right.attach(3);
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  
  
}


void onServoLeftChange() {
  left.write(servoLeft);
}


void onServoRightChange() {
  right.write(servoRight);
}


