// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


const char THING_ID[] = "579ba83f-258d-4ece-bc12-4459e6456c5a";

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)

void onServoLeftChange();
void onServoRightChange();

int servoLeft;
int servoRight;

void initProperties(){

  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(servoLeft, READWRITE, ON_CHANGE, onServoLeftChange);
  ArduinoCloud.addProperty(servoRight, READWRITE, ON_CHANGE, onServoRightChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
